delete from GENRES;
ALTER TABLE GENRES ALTER COLUMN GENRE_ID RESTART WITH 1;

delete from USERS;
ALTER TABLE USERS ALTER COLUMN USER_ID RESTART WITH 1;

delete from FILMS;
ALTER TABLE FILMS ALTER COLUMN FILM_ID RESTART WITH 1;

delete from RATINGS;
ALTER TABLE RATINGS ALTER COLUMN MPA_ID RESTART WITH 1;

INSERT INTO GENRES (NAME) VALUES ('Комедия');
INSERT INTO GENRES (NAME) VALUES ('Драма');
INSERT INTO GENRES (NAME) VALUES ('Мультфильм');
INSERT INTO GENRES (NAME) VALUES ('Триллер');
INSERT INTO GENRES (NAME) VALUES ('Документальный');
INSERT INTO GENRES (NAME) VALUES ('Боевик');

INSERT INTO RATINGS (NAME) VALUES ('G');
INSERT INTO RATINGS (NAME) VALUES ('PG');
INSERT INTO RATINGS (NAME) VALUES ('PG-13');
INSERT INTO RATINGS (NAME) VALUES ('R');
INSERT INTO RATINGS (NAME) VALUES ('NC-17');
