drop all objects;

create table if not EXISTS genres
(
    genre_id int generated by default as identity primary key,
    name     varchar(255)
);

create table if not EXISTS ratings
(
    MPA_ID int generated by default as identity primary key,
    name   varchar(255)
);

create table if not EXISTS films
(
    film_id      int generated by default as identity primary key,
    name         varchar(200),
    description  varchar(200),
    release_date DATE,
    duration     INTEGER,
    mpa_id       INTEGER NOT NULL REFERENCES ratings (mpa_id)
);

create table if not EXISTS users
(
    user_id  int generated by default as identity primary key,
    email    varchar(255) NOT NULL,
    login    varchar(255) NOT NULL,
    name     varchar(255),
    birthday date
);

create table if not EXISTS film_genres
(
    id       int generated by default as identity primary key,
    film_id  INTEGER not null REFERENCES films (film_id),
    genre_id INTEGER not null REFERENCES genres (genre_id)

);

create table if not EXISTS friends
(
    id        int generated by default as identity primary key not null,
    user_id   INTEGER                                          not null REFERENCES users (user_id),
    friend_id INTEGER                                          not null REFERENCES users (user_id)
);

create table if not EXISTS film_likes
(
    id      int generated by default as identity primary key not null,
    film_id INTEGER                                          not null REFERENCES films (film_id),
    user_id INTEGER                                          not null REFERENCES users (user_id)
);